---
name: "hpeov-alarms"
description: "Get HPE OneView alarms and load mongo databases."
enabled: false

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    delta: 5
    unit: minutes

action:
  ref: "hpeoneview.get-hpeov-alarms"
